/*
 *  bugsee.h
 *  bugsee-ffi
 *
 *  Copyright © 2026 Bugsee. All rights reserved.
 *
 *  GENERATED by cbindgen from crates/bugsee-ffi/src/lib.rs — do not edit by
 *  hand. Regenerate with scripts/gen-ffi-header.sh; CI fails if this file and
 *  the Rust source disagree.
 *
 *  C ABI for the Bugsee Rust SDK. Link against libbugsee_ffi (static or dynamic).
 *  Every function is panic-safe: a Rust panic never crosses this boundary — it
 *  is contained and reported as BUGSEE_PANIC.
 */

#ifndef BUGSEE_H
#define BUGSEE_H

#include <stdint.h>

/*
 Log level for [`bugsee_log`]: errors.
 */
#define BUGSEE_LEVEL_ERROR 1

/*
 Log level for [`bugsee_log`]: warnings.
 */
#define BUGSEE_LEVEL_WARNING 2

/*
 Log level for [`bugsee_log`]: informational messages.
 */
#define BUGSEE_LEVEL_INFO 3

/*
 Log level for [`bugsee_log`]: debugging output.
 */
#define BUGSEE_LEVEL_DEBUG 4

/*
 Log level for [`bugsee_log`]: verbose output.
 */
#define BUGSEE_LEVEL_VERBOSE 5

/*
 Result of an FFI call.
 */
enum BugseeStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  BUGSEE_STATUS_OK = 0,
  BUGSEE_STATUS_INVALID_ARGUMENT = 1,
  BUGSEE_STATUS_INTERNAL_ERROR = 2,
  /*
   A Rust panic was contained at the boundary.
   */
  BUGSEE_STATUS_PANIC = 3,
  BUGSEE_STATUS_NOT_LAUNCHED = 4,
  /*
   The SDK is launched but a `flush` did not drain before its timeout.
   */
  BUGSEE_STATUS_TIMEOUT = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum BugseeStatus BugseeStatus;
#else
typedef int32_t BugseeStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Launch the SDK with default options for `app_token`.

 # Safety
 `app_token` must be a valid NUL-terminated C string or null.
 */
BugseeStatus bugsee_launch(const char *app_token);

/*
 Launch with an explicit API endpoint override (for testing / self-hosting).

 # Safety
 Both pointers must be valid NUL-terminated C strings or null.
 */
BugseeStatus bugsee_launch_with_endpoint(const char *app_token, const char *endpoint);

/*
 Stop the SDK, flushing pending work.
 */
BugseeStatus bugsee_stop(void);

/*
 Whether the SDK is launched and not paused (1 = yes, 0 = no).
 */
int32_t bugsee_is_active(void);

/*
 Pause capture.
 */
BugseeStatus bugsee_pause(void);

/*
 Resume capture.
 */
BugseeStatus bugsee_resume(void);

/*
 Log a message at `level` (1=Error … 5=Verbose).

 # Safety
 `message` must be a valid NUL-terminated C string or null.
 */
BugseeStatus bugsee_log(int32_t level, const char *message);

/*
 Record a developer event.

 # Safety
 `name` must be a valid NUL-terminated C string or null.
 */
BugseeStatus bugsee_event(const char *name);

/*
 Record a developer event with a JSON object of parameters.

 # Safety
 Both pointers must be valid NUL-terminated C strings or null.
 */
BugseeStatus bugsee_event_with_params(const char *name, const char *params_json);

/*
 Record a named value trace (value is a JSON scalar/array/object).

 # Safety
 Both pointers must be valid NUL-terminated C strings or null.
 */
BugseeStatus bugsee_trace(const char *name, const char *value_json);

/*
 Set the user identifier.

 # Safety
 `email` must be a valid NUL-terminated C string or null.
 */
BugseeStatus bugsee_set_email(const char *email);

/*
 Set a report-level attribute (value is a JSON value).

 # Safety
 Both pointers must be valid NUL-terminated C strings or null.
 */
BugseeStatus bugsee_set_attribute(const char *key, const char *value_json);

/*
 Report a handled exception (name + reason) from the host language.

 # Safety
 Both pointers must be valid NUL-terminated C strings or null.
 */
BugseeStatus bugsee_capture_exception(const char *name, const char *reason);

/*
 Trigger an immediate manual report.
 */
BugseeStatus bugsee_upload(void);

/*
 Block until pending work drains, or `timeout_ms` elapses. Returns `Ok` on a
 full drain, `Timeout` if the SDK is launched but the queue did not drain in
 time, or `NotLaunched` if the SDK was never launched (F1).
 */
BugseeStatus bugsee_flush(uint32_t timeout_ms);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BUGSEE_H */
